version: 2
jobs:
  deploy:
    docker:
      - image: docker:18.06-git
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: docker build -t blogbase .
      - run:
          name: Login to docker hub
          command: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - run:
          name: Push docker image to docker hub
          command: |
            REVISION_TAG=$CIRCLE_SHA1
            docker tag blogbase $DOCKER_HUB_USERNAME/blogbase:latest
            docker push $DOCKER_HUB_USERNAME/blogbase:latest
workflows:
  version: 2
  build_deploy:
    jobs:
      - deploy:
          context: edeas123
          filters:
            branches:
              only:
                - master
